name: CI-CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up to JDK 21
        uses: actions/setup-java@v3  
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: make.application.yml
        run: |
          cd ./src/main/resources
          New-Item -Path "./application.yml" -ItemType "File" -Force
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: bootjar

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/vitamatch .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/vitamatch

      # SSH로 Windows 서버에 배포
      - name: Save SSH key to file
        run: |
          $key = "${{ secrets.SSH_PRIVATE_KEY }}"
          $key | Out-File -FilePath $env:USERPROFILE\.ssh\id_rsa -Encoding ascii
          icacls $env:USERPROFILE\.ssh\id_rsa /inheritance:r /grant:r "${env:USERNAME}:(R)"
          echo "Saved SSH key"

      - name: Create known_hosts file
        run: |
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> $env:USERPROFILE\.ssh\known_hosts

      - name: Connect to Windows Server and Run Command
        run: |
          ssh -i $env:USERPROFILE\.ssh\id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "powershell -Command \"Write-Output '✅ 윈도우 서버에 접속 성공!'; Get-Date\""
